#!/bin/bash
set -e

rm -rf images

pushd ../server/
rm -rf dist
python3 setup.py sdist
popd

pushd ../client
grunt distclean || true
npm install
grunt prereq
grunt build
popd

cp ../server/dist/*.tar.gz extras/
cp ../client/dist/*.tar.gz extras/

source ./private.conf

D=$'\001'
PATTERN='s'$D'MYSQL_PASSWORD'$D$MYSQL_PASSWORD$D'g;s'$D'ROOT_PASSWORD'$D$ROOT_PASSWORD$D'g;s'$D'AMS_PASSWORD'$D$AMS_PASSWORD$D'g'
sed $PATTERN profiles/ams.preseed.template > profiles/ams.preseed
mkdir -p extras/root/etc/init.d/
sed $PATTERN firstboot > extras/root/etc/init.d/firstboot
chmod +x extras/root/etc/init.d/firstboot

cp $PUBLIC_KEY extras/authorized_keys
rm -rf extras/root/etc/ssl
mkdir -p extras/root/etc/ssl/private
mkdir -p extras/root/etc/ssl/certs
cp $SERVER_KEY extras/root/etc/ssl/private/ams-client.key.pem
chmod 400 extras/root/etc/ssl/private/ams-client.key.pem
cp $SERVER_CERT extras/root/etc/ssl/certs/ams-client.cert.pem
cp $CA_CHAIN extras/root/etc/ssl/certs/ca-chain.cert.pem
if [ "$SSL" = true ]
then
	touch ./extras/scripts/ssl_flag
else
	rm -f ./extras/scripts/ssl_flag
fi

tar czvf extras.tar.gz extras/

build-simple-cdd
build-simple-cdd --conf ./ams.cdd.conf --force-preseed
