#!/usr/bin/env python3
# -*- coding: utf-8; -*-
#
# Copyright (C) 2014-2016  DING Changchang (of Canaan Creative)
#
# This file is part of Avalon Management System (AMS).
#
# AMS is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# AMS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with AMS. If not, see <http://www.gnu.org/licenses/>.

import sys
import json
import os

from ams.log import log


cfgfile = os.path.join(os.environ.get('VIRTUAL_ENV') or '/', 'etc/ams.conf')


def readCfg(filename):
    import configparser
    config = configparser.ConfigParser(interpolation=None)
    config.read(filename, encoding="utf8")
    return config


def validIP(ip):
    if ip[0] == '[' and ip[-1] == ']':
        part = ip[1:-1].split(':')
        if len(part) > 8:
            return False
        for p in part:
            if p == '':
                continue
            if int(p, 16) > 0xffff:
                return False
    else:
        part = ip.split('.')
        if len(part) != 4:
            return False
        for p in part:
            if int(p) > 255:
                return False
    return True


def ipDecode(s):
    if ':' in s and s[0] != '[':
        ip, port = s.split(':')
        port = int(port)
        if port < 0 or port > 65535 or not validIP(ip):
            return False
    elif s[1] == '[' and s[-1] != ']':
        tmp = s.split(']')
        ip = '{}]'.format(tmp[0])
        port = int(tmp[1][1:])
        if port < 0 or port > 65535 or not validIP(ip):
            return False
    else:
        ip = s
        port = None
        if not validIP(ip):
            return False
    return (ip, port)


def update(argv):
    import datetime
    from multiprocessing import Process

    from ams.farm import Farm
    from ams.pool import update_poolrate
    from ams.sql import sql_handler, DataBase, SQLQueue

    cfg = readCfg(cfgfile)
    db = cfg['DataBase']
    farm_type = cfg['Farm']['type']

    database = DataBase(db)
    database.connect()
    controllerList = database.run(
        'select', 'controller_config', ['ip', 'port', 'mods'])
    if not controllerList:
        print("No miner found.\n Run subcommand 'controller' to add.")
        exit()

    miners = [
        {
            'ip': m[0],
            'port': m[1],
            # 'mods': [int(mod) for mod in m[2].split(',')]
            'mods': m[2],
        }
        for m in controllerList
    ]
    myFarm = Farm(miners, farm_type)

    poolList = database.run(
        'select', 'pool_config',
        ['name', 'user', 'worker', 'key', 'seckey']
    )
    # TODO: should automatically get worker name from cgminer api
    if not poolList:
        pools = []
    else:
        pools = [
            {
                'name': p[0],
                'user': p[1],
                'worker': p[2],
                'key': p[3],
                'seckey': p[4]
            } for p in poolList
        ]
    database.disconnect()

    now = '{:%Y-%m-%d %H:%M:%S}'.format(datetime.datetime.now())
    sql_queue = SQLQueue()

    farm_process = Process(
        target=myFarm.run,
        args=(now, sql_queue, 5, 100)
    )
    pool_process = Process(
        target=update_poolrate,
        args=(pools, now, db, 3)
    )
    db_process = Process(
        target=sql_handler,
        args=(sql_queue, db, int(db['thread_num']))
    )
    db_process.start()
    pool_process.start()
    farm_process.start()
    pool_process.join()
    farm_process.join()
    db_process.join()


def fetch(argv):
    # using jq to reformat the output is recommended
    from ams.miner import Miner
    import json

    result = ipDecode(argv[0])
    if not result:
        exit()
    ip = result[0]
    port = result[1] or 4028
    miner = Miner(ip, port, None, False)
    command = argv[1]
    if len(argv) == 2:
        parameter = None
    else:
        parameter = argv[2]
    print(json.dumps(miner.put(command, parameter)))


def config(argv):
    from ams.sql import DataBase
    from ams.luci import LuCI

    data = []
    if argv[1] == '-f':
        with open(argv[2], 'r') as f:
            for d in f.readlines():
                data.append({
                    'lib': d.split(' ')[0],
                    'method': d.split(' ')[1],
                    'param': [' '.join(d.split(' ')[2:])]
                })
    else:
        data.append({
            'lib': argv[1],
            'method': argv[2],
            'param': [argv[3]],
        })

    if argv[0] != "all":
        result = ipDecode(argv[0])
        if not result:
            exit()
        ip, port = result
        clause = "`ip` = '{}'".format(ip)

        db = readCfg(cfgfile)['DataBase']

        database = DataBase(db)
        database.connect()
        minerList = database.run(
            'select', 'controller_config', ['password'], clause)
        database.disconnect()
        if not minerList:
            exit()
        password = minerList[0][0]

        luci = LuCI(ip, port, password)
        luci.auth()
        for d in data:
            print(json.dumps(luci.put(d['lib'], d['method'], d['param'])))

    else:
        db = readCfg(cfgfile)['DataBase']
        database = DataBase(db)
        database.connect()
        minerList = database.run(
            'select', 'controller_config',
            ['ip', 'password']
        )
        database.disconnect()
        if not minerList:
            exit()
        # TODO: threading


def controller(argv):
    import tempfile
    import subprocess
    import re
    from ams.sql import DataBase

    db = readCfg(cfgfile)['DataBase']

    database = DataBase(db)
    database.connect()
    minerList = database.run(
        'select', 'controller_config',
        ['ip', 'port', 'mods']
    )

    with tempfile.NamedTemporaryFile(mode='w+', suffix='.ams') as temp:
        temp.write('#ip\tport\tmods')
        if minerList:
            temp.write('\n')
            temp.write(
                '\n'.join('\t'.join(str(i) for i in m if i is not None)
                          for m in minerList)
            )
        temp.write('\n')
        temp.flush()
        subprocess.call(['vim', temp.name])
        temp.seek(0)
        cfg = temp.readlines()
    pattern = re.compile(
        r'\s*(?P<ip>[0-9a-fA-F.:\[\]]+)\s+'
        '(?P<port>[0-9]+)\s+'
        '(?P<mods>[0-9]+)\s*', re.X
    )

    result = []
    for c in cfg:
        if len(c.lstrip()) == 0 or c.lstrip()[0] == '#':
            continue
        match = re.match(pattern, c)
        if match is None:
            result = None
            break
        ip = match.group('ip')
        port = int(match.group('port'))

        if not validIP(ip) or port > 65535:
            result = None
            break

        result.append({
            "ip": ip,
            "port": port,
            "mods": match.group('mods')
        })

    if result is None:
        print('Invalid configuration.')
        database.disconnect()
        exit()

    database.run('raw', 'DROP TABLES IF EXISTS controller_config')
    database.run('create', 'controller_config', [
        {"name": "ip", "type": "VARCHAR(40)"},
        {"name": "port", "type": "SMALLINT UNSIGNED"},
        {"name": "mods", "type": "SMALLINT UNSIGNED"}
    ])
    for r in result:
        database.run(
            'insert', 'controller_config', list(r.keys()), list(r.values()))
    database.commit()
    database.disconnect()


def pool(argv):
    import tempfile
    import subprocess
    import re
    from ams.sql import DataBase

    db = readCfg(cfgfile)['DataBase']

    database = DataBase(db)
    database.connect()
    poolList = database.run(
        'select', 'pool_config',
        ['name', 'address', 'user', 'worker', 'key', 'seckey']
    )

    with tempfile.NamedTemporaryFile(mode='w+', suffix='.ams') as temp:
        temp.write('#name\taddress\tuser\tworker\tkey\tseckey')
        if poolList:
            temp.write('\n')
            temp.write(
                '\n'.join('\t'.join(i for i in m if i is not None)
                          for m in poolList)
            )
        temp.write('\n')
        temp.flush()
        subprocess.call(['vim', temp.name])
        temp.seek(0)
        cfg = temp.readlines()

    pattern = re.compile(
        r'\s*(?P<name>btcchina|kano|kano_a|ghash|cksolo)\s+'
        '(?P<address>[^\s]+)\s+'
        '(?P<user>[^\s]+)\s+'
        '(?P<worker>[^\s]+)\s+'
        '(?P<key>[^\s]+)'
        '(\s+(?P<seckey>[^\s]+))?\s*', re.X
    )

    result = []
    for c in cfg:
        if len(c.lstrip()) == 0 or c.lstrip()[0] == '#':
            continue
        match = re.match(pattern, c)
        if match is None:
            result = None
            break
        name = match.group('name')
        address = match.group('address')
        user = match.group('user')
        worker = match.group('worker')
        key = match.group('key')
        seckey = match.group('seckey')
        result.append({
            "name": name, "address": address, "user": user,
            "worker": worker, "key": key, "seckey": seckey
        })

    if result is None:
        print('Invalid configuration.')
        database.disconnect()
        exit()

    database.run('raw', 'DROP TABLES pool_config')
    database.run('create', 'pool_config', [
        {"name": "name", "type": "VARCHAR(16)"},
        {"name": "address", "type": "VARCHAR(64)"},
        {"name": "user", "type": "VARCHAR(64)"},
        {"name": "worker", "type": "VARCHAR(4096)"},
        {"name": "key", "type": "VARCHAR(64)"},
        {"name": "seckey", "type": "VARCHAR(64)"}
    ])
    for r in result:
        database.run('insert', 'pool_config', list(r.keys()), list(r.values()))
    database.commit()
    database.disconnect()


def alert(argv):
    pass


def report(argv):
    from ams.report import sendReport
    cfg = readCfg(cfgfile)
    sendReport(cfg)


def init(argv):
    from ams.sql import DataBase
    db = readCfg(cfgfile)['DataBase']
    database = DataBase(db)
    database.connect()
    database.run('create', 'controller_security', [
        {'name': 'ip', 'type': 'VARCHAR(40)'},
        {'name': 'password', 'type': 'VARCHAR(64) DEFAULT NULL'},
    ], 'PRIMARY KEY(`ip`)')
    database.run('create', 'user', [
        {'name': 'username', 'type': 'VARCHAR(64)'},
        {'name': 'password', 'type': 'CHAR(64)'},
    ], 'PRIMARY KEY(`username`)')

    database.run('create', 'order', [
        {'name': 'order_id', 'type': 'VARCHAR(64)'},
        {'name': 'doc_id', 'type': 'VARCHAR(64)'},
        {'name': 'quantity', 'type': 'INT UNSIGNED'},
        {'name': 'note', 'type': 'VARCHAR(128)'},
    ], 'PRIMARY KEY(`order_id`)')

    database.run('create', 'product', [
        {'name': 'product_sn', 'type': 'VARCHAR(128)'},
        {'name': 'order_sn', 'type': 'VARCHAR(128)'},
        {'name': 'batch', 'type': 'VARCHAR(64)'},
        {'name': 'time', 'type': 'TIMESTAMP'},
    ], 'PRIMARY KEY(`product_sn`)')

    database.run('create', 'component', [
        {'name': 'component_sn', 'type': 'VARCHAR(128)'},
        {'name': 'component_id', 'type': 'INT UNSIGNED'},
        {'name': 'product_sn', 'type': 'VARCHAR(128)'},
        {'name': 'note', 'type': 'VARCHAR(128)'},
        {'name': 'active_time', 'type': 'TIMESTAMP'},
        {'name': 'revoke', 'type': 'BOOLEAN DEFAULT 0'},
        {'name': 'revoke_time', 'type': 'TIMESTAMP DEFAULT 0'},
    ], 'PRIMARY KEY(`component_sn`, `product_sn`, `active_time`)')

    database.run('create', 'code_rule', [
        {'name': 'header', 'type': 'VARCHAR(128) NOT NULL'},
        {'name': 'name', 'type': 'VARCHAR(128)'},
        {'name': 'model', 'type': 'VARCHAR(128)'},
        {'name': 'time', 'type': 'TIMESTAMP DEFAULT 0'},
    ], 'PRIMARY KEY(`header`, `time`)')

    database.run('create', 'depend_rule', [
        {'name': 'component_header', 'type': 'VARCHAR(128)'},
        {'name': 'component_id', 'type': 'VARCHAR(128)'},
        {'name': 'product_header', 'type': 'VARCHAR(128)'},
        {'name': 'time', 'type': 'TIMESTAMP DEFAULT 0'},
    ], 'PRIMARY KEY(`component_id`, `product_header`, `time`)')

    database.commit()
    database.disconnect()


def adduser(argv):
    import hashlib
    from ams.sql import DataBase

    db = readCfg(cfgfile)['DataBase']
    database = DataBase(db)
    database.connect()

    username = argv[0]
    password = argv[1]

    database.run(
        'insert', 'user',
        ['username', 'password'],
        [username, hashlib.sha256(password.encode()).hexdigest()]
    )
    database.commit()
    database.disconnect()


if __name__ == '__main__':
    doc = '''\
THIS IS THE DOC.'''

    if (len(sys.argv) < 2):
        print(doc)
        exit()

    log()
    if (sys.argv[1] == 'init'):
        init(sys.argv[2:])
    elif (sys.argv[1] == 'adduser'):
        adduser(sys.argv[2:])
    elif (sys.argv[1] == 'controller'):
        controller(sys.argv[2:])
    elif (sys.argv[1] == 'pool'):
        pool(sys.argv[2:])
    elif (sys.argv[1] == 'fetch'):
        fetch(sys.argv[2:])
    elif (sys.argv[1] == 'update'):
        update(sys.argv[2:])

    elif (sys.argv[1] == 'config'):
        config(sys.argv[2:])
    elif (sys.argv[1] == 'alert'):
        alert(sys.argv[2:])
    elif (sys.argv[1] == 'report'):
        report(sys.argv[2:])
    else:
        print(doc)
