database:
    user: ams
    password: !!str "DB_PASSWORD"
    database: ams
    thread_num: 100
folder:
    archive: /var/ams/csv
    image: /var/ams/img
cgminer:
    retry: 5
    thread_num: 100
web:
    method: auto
    # ip|module|auto
miner:
    - ip: 192.168.2.21
      port: 4028
      # device: Avalon4
      mods:
          - num: 5
            pos: ["(1; 1; 1; 1-5)"]
            # dna: ["01318a62cc593837", "0131c13434ba5281", "013709c8904aa7c8", "01384d92c1e58f1d", "01309ab1e9bf70a1"]
          - num: 5
            pos: ["(1; 1; 2; *)"]
          - num: 5
            pos: ["(1; 1; 3; *)"]
      #position: ["(1; 1; *; *)"]
    - ip: 192.168.2.22
      port: 4028
      mods:
          - num: 5
            pos: ["(1; 2; 1; *)"]
          - num: 5
            pos: ["(1; 2; 2; *)"]
          - num: 5
            pos: ["(1; 2; 3; *)"]
      #position: ["(1; 2; *; *)"]
    - ip: 192.168.2.23
      port: 4028
      mods:
          - num: 5
            pos: ["(1; 3; 1; *)"]
          - num: 5
            pos: ["(1; 3; 2; *)"]
          - num: 5
            pos: ["(1; 3; 3; *)"]
      #position: ["(1; 3; *; *)"]
    - ip: 192.168.2.24
      port: 4028
      mods:
          - num: 5
            pos: ["(1; 4; 1; *)"]
          - num: 5
            pos: ["(1; 4; 2; *)"]
          - num: 5
            pos: ["(1; 4; 3; *)"]
      #position: ["(1; 4; *; *)"]
    - ip: 192.168.2.25
      port: 4028
      mods:
          - num: 5
            pos: ["(1; 5; 1; *)"]
          - num: 5
            pos: ["(1; 5; 2; *)"]
          - num: 5
            pos: ["(1; 5; 3; *)"]
      #position: ["(1; 5; 2; 1-2)"]
farm:
    # zone #1
    - zone: 1
      shelf: 5
      layer: 3
      storage: 5
    ## zone #2 #3 #4
    # - zone: 3
    #   shelf: 4
    #   layer: 2
    #   storage: 6
    ## zone #5
    # - zone: 1
    #   shelf: 3
    #   layer: 3
    #   storage: 7
